export const LANGUAGES: Record<string, { name: string; nativeName: string }> = {
  en: { name: 'English', nativeName: 'English' },
  pt: { name: 'Portuguese', nativeName: 'Português' },
  es: { name: 'Spanish', nativeName: 'Español' },
  fr: { name: 'French', nativeName: 'Français' },
  de: { name: 'German', nativeName: 'Deutsch' },
  it: { name: 'Italian', nativeName: 'Italiano' },
  ru: { name: 'Russian', nativeName: 'Русский' },
  ja: { name: 'Japanese', nativeName: '日本語' },
  ko: { name: 'Korean', nativeName: '한국어' },
  zh: { name: 'Chinese', nativeName: '中文' },

  ar: { name: 'Arabic', nativeName: 'العربية' },
  nl: { name: 'Dutch', nativeName: 'Nederlands' },
  pl: { name: 'Polish', nativeName: 'Polski' },
  tr: { name: 'Turkish', nativeName: 'Türkçe' },
  sv: { name: 'Swedish', nativeName: 'Svenska' },
  da: { name: 'Danish', nativeName: 'Dansk' },
  no: { name: 'Norwegian', nativeName: 'Norsk' },
  fi: { name: 'Finnish', nativeName: 'Suomi' },

  cs: { name: 'Czech', nativeName: 'Čeština' },
  el: { name: 'Greek', nativeName: 'Ελληνικά' },
  he: { name: 'Hebrew', nativeName: 'עברית' },
  hi: { name: 'Hindi', nativeName: 'हिन्दी' },
  hu: { name: 'Hungarian', nativeName: 'Magyar' },
  id: { name: 'Indonesian', nativeName: 'Bahasa Indonesia' },
  ms: { name: 'Malay', nativeName: 'Bahasa Melayu' },
  ro: { name: 'Romanian', nativeName: 'Română' },
  sk: { name: 'Slovak', nativeName: 'Slovenčina' },
  uk: { name: 'Ukrainian', nativeName: 'Українська' },
  vi: { name: 'Vietnamese', nativeName: 'Tiếng Việt' },
  th: { name: 'Thai', nativeName: 'ไทย' },
  ca: { name: 'Catalan', nativeName: 'Català' },
  eu: { name: 'Basque', nativeName: 'Euskara' },
  gl: { name: 'Galician', nativeName: 'Galego' },
  hr: { name: 'Croatian', nativeName: 'Hrvatski' },
  sr: { name: 'Serbian', nativeName: 'Српски' },
  sl: { name: 'Slovenian', nativeName: 'Slovenščina' },
  bg: { name: 'Bulgarian', nativeName: 'Български' },
  et: { name: 'Estonian', nativeName: 'Eesti' },
  lv: { name: 'Latvian', nativeName: 'Latviešu' },
  lt: { name: 'Lithuanian', nativeName: 'Lietuvių' },
  fa: { name: 'Persian', nativeName: 'فارسی' },
  bn: { name: 'Bengali', nativeName: 'বাংলা' },
  ta: { name: 'Tamil', nativeName: 'தமிழ்' },
  te: { name: 'Telugu', nativeName: 'తెలుగు' },
  ur: { name: 'Urdu', nativeName: 'اردو' },
}